### ISSUE TITLE
Token is cached? Or response cached?

### ISSUE THREAD

**Issue by mariano-dagostino** [e0ipso/simple_oauth#17]
I will try to explain my situation as clear as possible.

Using jsonapi I'm listing articles:

If Article with NID = 1 is published then `/api/node/article/1?_format=json` will return the content of the entity.

Then, I unpublish the node and try to get the resource again. `/api/node/article/1?_format=json` returns 403. Ok this works as expected.

Now, I'm using `simple_oauth` and I created a resource called `view_unpublish_content` with the permission `bypass access content`.

I repeat the process now sending the Bearer token and I'm able to get the content of the node.

Now comes the weird thing. After I sent the token the first time, each other request to the same endpoint will return data,  even if I don't send the authorization token

It seems the response is cached, therefore any other anonymous user can see the result without use a token.

Maybe the issue is not due this module but a core issue, but I would to get some advice to see what is happening here.

**Comment by e0ipso** [comment]
Can you please try the same with page cache off? Also try with dynamic page cache on/off.

**Comment by e0ipso** [comment]
That's for debugging purposes

**Comment by mariano-dagostino** [comment]
Te debo una cerveza

**Comment by e0ipso** [comment]
> Te debo una cerveza

_Me parece genial! Cerveza aceptada. ;-)_

Does that mean that you found the root cause? :-)

**Comment by mariano-dagostino** [comment]
Deactivating dynamic page cache fixes the issue. However maybe jsonapi (or simple_oauth) should disable the page cache when using tokens. What do you think?

**Comment by e0ipso** [comment]
That may sound like a missing cache context.

**Comment by mariano-dagostino** [comment]
Ok, I'm closing this and will open a new bug to see analyze the interaction with Dynamic Page Cache.

**Comment by e0ipso** [comment]
That will be fantastic! Thanks @mariano-dagostino.
