### ISSUE TITLE
Remove deleteDuplicates

### ISSUE THREAD

**Issue by sblommaert** [e0ipso/simple_oauth#23]
When multiple applications are using an API on behalf of the same user (for example Android app and Web app), they invalidate the refresh token when asking for a new access token. 

The deleteDuplicates function allows only 1 pair of tokens for each resource. Allowing multiple refresh / access tokens at the same time could solve this.

Is there a reason to remove the duplicates?

**Comment by e0ipso** [comment]
One token means credentials for a resource. Why do you need more than one? You should be able to share the token among applications, shouldn't you?

**Comment by sblommaert** [comment]
Of course the tokens can be shared among applications. But currently when 1 of the applications requests a new acces token (because the old one expired) the following happens:
- A new access token is generated
- The new refresh token is generated for the access token
- The old access/refresh tokens are deleted

This last step is a problem, because all other applications still use the old refresh token (which now doesn't exist anymore) requiring the user to log in again. 

When using a android app and a web application with a refresh token for a couple of days, this means the user is logged out of the app everytime the user uses the webapp.

Of course it is possible to create a resource for each application, which allows multiple tokens (1 pair per resource), but since the permissions on those resources are the same this feels kind of wrong? 
Is this last part by design? I think having to create resources for each application might be a bit overkill. 

Unless there is a security issue when having multiple tokens per resource (which I'm not really seeing at the moment), I think allowing this will make the module easier to use.

**Comment by e0ipso** [comment]
You built a strong case here. Thank you for taking the time!

Would you care to write a PR to include those changes?

**Comment by sblommaert** [comment]
No problem! https://github.com/e0ipso/simple_oauth/pull/24

Are you planning on creating a dev branch on drupal.org with the latest changes from github? I'm currently pulling the module in through composer from https://packages.drupal.org/8. Maybe this helps people testing the latest version.

**Comment by e0ipso** [comment]
This was fixed in #24.
