### ISSUE TITLE
Option to invalidate token

### ISSUE THREAD

**Issue by niksmac** [e0ipso/simple_oauth#4]
what about an option to invalidate token

make a request against `/simple-oauth/invalidate_token` providing the header `Authorization: Bearer {YOUR REFRESH TOKEN}` or `{{YOUR ACCESS TOKEN}}`

**Comment by e0ipso** [comment]
Tokens are entities. You should be able to expose the `DELETE` method on them like any other REST resource.

**Comment by niksmac** [comment]
ah, cool lets close this issue.
